name: Workflow with some inputs

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: "gimme repo name"
        required: true


jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Parse
        run: |
          REPO_NAME=$(basename "${{ inputs.repo_name }}")
          echo "REPO_NAME=$REPO_NAME" >> "$GITHUB_ENV"
      - name: Print
        run: |
          echo "Repo name: $REPO_NAME"