name: Workflow with some inputs

on:
  workflow_dispatch:
    inputs:
      variable:
        description: "This is choice"
        required: true
        default: "foo"
        type: choice
        options:
        - foo
        - bar-baz

jobs:
  my-job:
    runs-on: ubuntu-latest
    env:
      MY_ENV_VAR: woop/${{ inputs.variable }}/woop
      ORG: ${{ github.repository_owner }}
      REPO: pytest-split
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Name
        run: |
          echo "my env var: $MY_ENV_VAR"
          echo "org: $ORG"
      - name: Name 2
        run: gh repo create jerry-git/new-repo --private
